server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kthilina/microservice-projects/tree/master/spring-cloud-config-store/primary-config-store
          #username:
          #passphrase:


